version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste_laravel
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  webserver:
    image: nginx:alpine
    container_name: teste_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: teste_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "33061:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql